version: '3.8'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports: # Required plex ports
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment: # Set environment variables
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://${HOST}:32400/
    volumes:
      - ${DOCKER_VOLS}/plex/config:/config
      - ${TEMP_DOCKER_VOLS}/plex/temp:/transcode
      - ${MEDIA}:/data
    devices:
      - "/dev/dri:/dev/dri" # For HW transcoding